name: 部署博客到 GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出源码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 安装博客核心依赖
        run: |
          npm install

      - name: 编译静态网页
        run: |
          ./node_modules/hexo/bin/hexo clean
          ./node_modules/hexo/bin/hexo generate

      - name: 强制同步到博客主仓库
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          repository-name: yuejunonline/yuejunonline.github.io
          branch: master
          token: ${{ secrets.BLOG_TOKEN }}
          clean: true
