name: 部署博客到 GitHub Pages

on:
  push:
    branches:
      - main  # 触发条件：当你向 main 分支推送代码时

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出源码
        uses: actions/checkout@v3
        with:
          submodules: true 

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 安装依赖
        run: |
          npm install -g hexo-cli
          npm install

      - name: 生成网页
        run: |
          hexo clean
          hexo generate

      - name: 彻底覆盖旧博客
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          repository-name: yuejunonline/yuejunonline.github.io
          branch: master  # 你的旧仓库目前显示的分支是 master
          token: ${{ secrets.BLOG_TOKEN }} # 这里的名字必须和你之前在 Settings 里存的 Secret 名字一模一样
          clean: true
